/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./components/code-block/index.vue')['default']
    DocsLayout: typeof import('./components/docs-layout/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Icon: typeof import('./components/icon/icon.vue')['default']
    IndexOnce: typeof import('./components/docs-layout/navigation/index-once.vue')['default']
    Markdown: typeof import('./components/markdown/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundCodeOnce: typeof import('./components/code-block/sound-code-once.vue')['default']
    SoundPathOnce: typeof import('./components/code-block/sound-path-once.vue')['default']
    SvgIcon: typeof import('./components/icon/svg-icon.vue')['default']
    TreeOnce: typeof import('./components/docs-layout/navigation/tree-once.vue')['default']
  }
}
