/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: (typeof import('./components/code-block/index.vue'))['default']
    DocsLayout: (typeof import('./components/docs-layout/index.vue'))['default']
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDivider: (typeof import('element-plus/es'))['ElDivider']
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElEmpty: (typeof import('element-plus/es'))['ElEmpty']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    Icon: (typeof import('./components/icon/icon.vue'))['default']
    IndexOnce: (typeof import('./components/docs-layout/navigation/index-once.vue'))['default']
    Markdown: (typeof import('./components/markdown/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SoundCodeOnce: (typeof import('./components/code-block/sound-code-once.vue'))['default']
    SoundPathOnce: (typeof import('./components/code-block/sound-path-once.vue'))['default']
    SvgIcon: (typeof import('./components/icon/svg-icon.vue'))['default']
    TreeOnce: (typeof import('./components/docs-layout/navigation/tree-once.vue'))['default']
  }
}
