/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Application: (typeof import('./components/application/Application.vue'))['default']
    Aside: (typeof import('./components/layouts/default/aside/index.vue'))['default']
    Breadcrumb: (typeof import('./components/layouts/default/header/breadcrumb/index.vue'))['default']
    Code: (typeof import('./components/layouts/docsLayout/codeBlock/code.vue'))['default']
    CodeBlock: (typeof import('./components/layouts/docsLayout/codeBlock/index.vue'))['default']
    Default: (typeof import('./components/layouts/default/index.vue'))['default']
    DocsLayout: (typeof import('./components/layouts/docsLayout/index.vue'))['default']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    Feature: (typeof import('./components/layouts/default/feature/index.vue'))['default']
    Full: (typeof import('./components/layouts/default/tabs/full/index.vue'))['default']
    Header: (typeof import('./components/layouts/default/header/index.vue'))['default']
    Icon: (typeof import('./components/Icon/Icon.vue'))['default']
    Logo: (typeof import('./components/layouts/default/logo/index.vue'))['default']
    Main: (typeof import('./components/layouts/default/main/index.vue'))['default']
    Markdown: (typeof import('./components/layouts/docsLayout/markdown.vue'))['default']
    NavIcon: (typeof import('./components/layouts/default/navIcon/index.vue'))['default']
    Navigation: (typeof import('./components/layouts/docsLayout/navigation/index.vue'))['default']
    ParentLayout: (typeof import('./components/layouts/parentLayout/index.vue'))['default']
    Path: (typeof import('./components/layouts/docsLayout/codeBlock/path.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Set: (typeof import('./components/layouts/default/tabs/set/index.vue'))['default']
    Setting: (typeof import('./components/layouts/default/feature/setting/index.vue'))['default']
    SvgIcon: (typeof import('./components/Icon/SvgIcon.vue'))['default']
    Tabs: (typeof import('./components/layouts/default/tabs/index.vue'))['default']
    Theme: (typeof import('./components/layouts/default/theme/index.vue'))['default']
    Tree: (typeof import('./components/layouts/docsLayout/navigation/tree.vue'))['default']
    Trigger: (typeof import('./components/layouts/default/header/trigger/index.vue'))['default']
  }
}
