/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/application/Application.vue')['default']
    Aside: typeof import('./src/components/layouts/default/aside/index.vue')['default']
    Breadcrumb: typeof import('./src/components/layouts/default/header/breadcrumb/index.vue')['default']
    Default: typeof import('./src/components/layouts/default/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Feature: typeof import('./src/components/layouts/default/feature/index.vue')['default']
    Header: typeof import('./src/components/layouts/default/header/index.vue')['default']
    Logo: typeof import('./src/components/layouts/default/logo/index.vue')['default']
    ParentLayout: typeof import('./src/components/layouts/parentLayout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/layouts/default/feature/setting/index.vue')['default']
    Theme: typeof import('./src/components/layouts/default/feature/setting/theme/index.vue')['default']
    Trigger: typeof import('./src/components/layouts/default/header/trigger/index.vue')['default']
  }
}
