/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/application/Application.vue')['default']
    Aside: typeof import('./src/components/layouts/default/aside/index.vue')['default']
    Breadcrumb: typeof import('./src/components/layouts/default/header/breadcrumb/index.vue')['default']
    Code: typeof import('./src/components/layouts/docsLayout/codeBlock/code.vue')['default']
    CodeBlock: typeof import('./src/components/layouts/docsLayout/codeBlock/index.vue')['default']
    Default: typeof import('./src/components/layouts/default/index.vue')['default']
    DocsLayout: typeof import('./src/components/layouts/docsLayout/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Feature: typeof import('./src/components/layouts/default/feature/index.vue')['default']
    Full: typeof import('./src/components/layouts/default/tabs/full/index.vue')['default']
    Header: typeof import('./src/components/layouts/default/header/index.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    Logo: typeof import('./src/components/layouts/default/logo/index.vue')['default']
    Main: typeof import('./src/components/layouts/default/main/index.vue')['default']
    Markdown: typeof import('./src/components/layouts/docsLayout/markdown.vue')['default']
    NavIcon: typeof import('./src/components/layouts/default/navIcon/index.vue')['default']
    Navigation: typeof import('./src/components/layouts/docsLayout/navigation/index.vue')['default']
    ParentLayout: typeof import('./src/components/layouts/parentLayout/index.vue')['default']
    Path: typeof import('./src/components/layouts/docsLayout/codeBlock/path.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Set: typeof import('./src/components/layouts/default/tabs/set/index.vue')['default']
    Setting: typeof import('./src/components/layouts/default/feature/setting/index.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    Tabs: typeof import('./src/components/layouts/default/tabs/index.vue')['default']
    Theme: typeof import('./src/components/layouts/default/theme/index.vue')['default']
    Tree: typeof import('./src/components/layouts/docsLayout/navigation/tree.vue')['default']
    Trigger: typeof import('./src/components/layouts/default/header/trigger/index.vue')['default']
  }
}
